### ISSUE TITLE
Decide on a repo for frontend

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/prescriptions#13]
It likely won't be this one. 

To close, we will have also decided how we will do issue tracking, and document that.

**Comment by ayaleloehr** [comment]
Will be vets-website. Albert and Courtney are working on getting that set up and once it's more stable will move to there. for the time being, code is being done in `rx` and issues are being tracked in `vets-website`

**Comment by webinista** [comment]
Is there a point to keeping this repo around since we also have prescriptions-api?

**Comment by ayaleloehr** [comment]
No other than the fact that it's the thing holding waffle together, as the whole prescriptions waffle board was started from this repo. I will create another issue to delete this repo and fix waffle when I do. Reasonable?

**Comment by webinista** [comment]
Don't do any extra work on my account :-). If we still need it for Waffle, let's leave it where it is.
